# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywdocumentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/ywdocument'),
        ),
    ]
