# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='网站名')),
                ('url', models.URLField()),
                ('state', models.CharField(choices=[('1', '正常'), ('2', '异常')], max_length=2, verbose_name='状态')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='导航名称')),
                ('upper_business', models.IntegerField(blank=True, null=True, verbose_name='上级id')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='SiteNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='网站名')),
                ('url', models.URLField(verbose_name='url地址')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
