# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenavigation',
            name='business_type',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'other')], default=3, max_length=2, verbose_name='业务类型'),
        ),
        migrations.AddField(
            model_name='sitenavigation',
            name='img',
            field=models.ImageField(default='img/siteIndex/default.png', upload_to='img/siteIndex/'),
        ),
    ]
