# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0002_auto_20180321_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenavigation',
            name='introduction',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitenavigation',
            name='business_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('other', 'other')], default=3, max_length=5, verbose_name='业务类型'),
        ),
    ]
