# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicApp', '0003_auto_20180321_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenavigation',
            name='img',
            field=models.ImageField(default='img/siteIndex/default.jpg', upload_to='img/siteIndex/'),
        ),
    ]
