# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appmanagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=3, verbose_name='环境')),
                ('appName', models.CharField(max_length=25, verbose_name='应用名称')),
                ('code', models.CharField(max_length=10, verbose_name='应用编码')),
                ('operationsPersonnel', models.CharField(max_length=25, verbose_name='运维人员')),
                ('state', models.CharField(choices=[('1', '启用'), ('2', '停用')], default='1', max_length=2, verbose_name='状态')),
                ('ipOut', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('ipIn', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('path', models.CharField(max_length=50, verbose_name='应用部署路径')),
                ('deployName', models.CharField(max_length=25, verbose_name='应用部署名称')),
                ('port', models.IntegerField(default=0, verbose_name='监听端口')),
                ('urlLink', models.CharField(max_length=50, verbose_name='访问地址')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('code_state', models.CharField(choices=[('4', 'restart'), ('3', 'stop'), ('1', 'None'), ('2', 'start')], default='1', max_length=10, verbose_name='操作动作')),
                ('code_update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('code_content', models.CharField(blank=True, max_length=6, null=True, verbose_name='验证码')),
                ('code_send_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='发送内容')),
            ],
        ),
        migrations.CreateModel(
            name='viewlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=3, verbose_name='环境')),
                ('IP', models.GenericIPAddressField(verbose_name='IP')),
                ('SSHport', models.CharField(max_length=5, verbose_name='SSH端口')),
                ('username', models.CharField(max_length=30, verbose_name='登陆用户')),
                ('passwd', models.CharField(max_length=50, verbose_name='登陆密码')),
            ],
        ),
    ]
