# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressYunwei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('phone', models.CharField(max_length=30, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('position', models.CharField(max_length=30, verbose_name='岗位')),
                ('QQ', models.CharField(max_length=30, verbose_name='QQ')),
                ('note', models.CharField(max_length=30, verbose_name='备注')),
            ],
        ),
    ]
